DESTINY_VAULT = {
    "Aries": {
        "destiny_message": "You are the spark that ignites civilizations. Your destiny is to lead the charge into uncharted territory. The cosmos chose you to be first.",
        "power_mantra": "I am the fire that lights the way.",
        "lucky_number": 9,
        "lucky_color": "Red",
        "lucky_gem": "Diamond",
        "cosmic_mission": "To pioneer new paths and inspire others to follow their courage.",
        "past_life": "A warrior-king who united divided kingdoms under one banner of truth.",
        "future_prophecy": "Within three cosmic cycles, a great opportunity will arrive disguised as a challenge.",
    },
    "Taurus": {
        "destiny_message": "You are the anchor of the cosmos. Your destiny is to build lasting beauty and abundance that outlives generations. What you create shall stand eternal.",
        "power_mantra": "I am the mountain that endures all storms.",
        "lucky_number": 6,
        "lucky_color": "Green",
        "lucky_gem": "Emerald",
        "cosmic_mission": "To manifest abundance and teach the world the sacred art of patience.",
        "past_life": "A master architect who built temples connecting heaven and earth.",
        "future_prophecy": "The seeds you plant now in silence will bloom into your greatest triumph.",
    },
    "Gemini": {
        "destiny_message": "You are the messenger of the gods. Your destiny is to weave ideas across worlds and minds, birthing revolutions through the power of words.",
        "power_mantra": "I am the wind that carries sacred truth.",
        "lucky_number": 5,
        "lucky_color": "Yellow",
        "lucky_gem": "Agate",
        "cosmic_mission": "To bridge worlds through communication and awaken minds with cosmic knowledge.",
        "past_life": "A renowned scribe who preserved the wisdom of lost civilizations.",
        "future_prophecy": "A conversation you have soon will redirect the entire course of your destiny.",
    },
    "Cancer": {
        "destiny_message": "You are the cosmic womb from which new worlds are born. Your destiny is to nurture souls back to their divine wholeness. Love is your superpower.",
        "power_mantra": "I am the ocean that holds all life.",
        "lucky_number": 2,
        "lucky_color": "Silver",
        "lucky_gem": "Moonstone",
        "cosmic_mission": "To heal emotional wounds and create safe havens for lost souls.",
        "past_life": "A high priestess of the moon temple, keeper of ancient feminine wisdom.",
        "future_prophecy": "Your greatest love story — with yourself or another — is about to begin.",
    },
    "Leo": {
        "destiny_message": "You are the Sun made flesh. Your destiny is to shine so brightly that others remember their own light. The cosmos gave you a stage — use it.",
        "power_mantra": "I am the radiance of a thousand suns.",
        "lucky_number": 1,
        "lucky_color": "Gold",
        "lucky_gem": "Ruby",
        "cosmic_mission": "To lead with love, inspire with courage, and remind the world of its divine royalty.",
        "past_life": "A beloved emperor whose reign ushered in a golden age of arts and peace.",
        "future_prophecy": "Recognition that was delayed is arriving. Your crown is being prepared.",
    },
    "Virgo": {
        "destiny_message": "You are the sacred algorithm of the cosmos. Your destiny is to bring divine order to chaos and reveal the hidden perfection in all things.",
        "power_mantra": "I am the sacred pattern within all creation.",
        "lucky_number": 5,
        "lucky_color": "Indigo",
        "lucky_gem": "Sapphire",
        "cosmic_mission": "To heal systems, bodies, and minds through precise and loving attention.",
        "past_life": "A master healer in an ancient civilization who mapped the human energy field.",
        "future_prophecy": "Your skills are about to find their highest purpose in an unexpected arena.",
    },
    "Libra": {
        "destiny_message": "You are the divine scale of cosmic justice. Your destiny is to restore balance wherever you walk and create harmony between opposing forces.",
        "power_mantra": "I am the balance point between all worlds.",
        "lucky_number": 6,
        "lucky_color": "Pink",
        "lucky_gem": "Opal",
        "cosmic_mission": "To create beauty, restore justice, and weave love into every relationship.",
        "past_life": "A revered judge and peacemaker who ended ancient wars through diplomacy.",
        "future_prophecy": "A partnership forming now will become the greatest collaboration of your life.",
    },
    "Scorpio": {
        "destiny_message": "You are the phoenix of the zodiac. Your destiny is to die and be reborn, each time emerging more powerful. Your wounds are portals to your power.",
        "power_mantra": "I rise from every ending more powerful than before.",
        "lucky_number": 8,
        "lucky_color": "Crimson",
        "lucky_gem": "Obsidian",
        "cosmic_mission": "To transmute darkness into light and guide others through their deepest transformations.",
        "past_life": "A shaman who walked between the worlds of the living and the dead.",
        "future_prophecy": "The transformation you fear most holds the treasure you seek most.",
    },
    "Sagittarius": {
        "destiny_message": "You are the cosmic arrow shot toward the infinite. Your destiny is to explore beyond every boundary and return with wisdom for all of humanity.",
        "power_mantra": "I am the seeker who finds truth in every horizon.",
        "lucky_number": 3,
        "lucky_color": "Purple",
        "lucky_gem": "Turquoise",
        "cosmic_mission": "To expand human consciousness through adventure, philosophy, and sacred teaching.",
        "past_life": "A wandering sage who traveled the ancient world gathering and sharing divine wisdom.",
        "future_prophecy": "A journey — physical or spiritual — will unlock the next chapter of your destiny.",
    },
    "Capricorn": {
        "destiny_message": "You are the mountain of the cosmos. Your destiny is to climb to the summit of mastery and show others that discipline is the highest form of devotion.",
        "power_mantra": "I am the summit that touches the stars.",
        "lucky_number": 8,
        "lucky_color": "Brown",
        "lucky_gem": "Garnet",
        "cosmic_mission": "To build lasting legacies and demonstrate that earthly mastery is a spiritual path.",
        "past_life": "A wise elder statesman who guided an entire civilization through its darkest century.",
        "future_prophecy": "Years of silent effort are about to crystallize into undeniable achievement.",
    },
    "Aquarius": {
        "destiny_message": "You are the lightning bolt of the future striking the present. Your destiny is to revolutionize what humanity believes is possible.",
        "power_mantra": "I am the future arriving ahead of schedule.",
        "lucky_number": 4,
        "lucky_color": "Electric Blue",
        "lucky_gem": "Amethyst",
        "cosmic_mission": "To disrupt outdated systems and architect the future of human civilization.",
        "past_life": "A visionary inventor centuries ahead of their time, misunderstood but never silenced.",
        "future_prophecy": "Your most radical idea is your most important one. The world is finally ready.",
    },
    "Pisces": {
        "destiny_message": "You are the cosmic ocean dreaming itself awake. Your destiny is to dissolve boundaries between worlds and remind humanity of its divine, unified source.",
        "power_mantra": "I am the dream in which all souls swim.",
        "lucky_number": 7,
        "lucky_color": "Sea Green",
        "lucky_gem": "Aquamarine",
        "cosmic_mission": "To channel divine creativity and compassion into art, healing, and spiritual awakening.",
        "past_life": "A mystic poet whose words opened portals to other dimensions of consciousness.",
        "future_prophecy": "A creative vision arriving in your dreams holds the key to your earthly mission.",
    },
}


def calculate_destiny_vault(zodiac_sign: str) -> dict:
    return DESTINY_VAULT.get(zodiac_sign, DESTINY_VAULT["Aries"])